const categoriesData = [
  {
    id: 1,
    name: "Home",
    image_uri: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=400&fit=crop",
  },
  {
    id: 2,
    name: "Gadgets",
    image_uri: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=400&fit=crop",
  },
  {
    id: 3,
    name: "Beauty",
    image_uri: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop",
  },
  {
    id: 4,
    name: "Fashion",
    image_uri: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=400&fit=crop",
  },
  {
    id: 5,
    name: "Mobiles",
    image_uri: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
  },
  {
    id: 6,
    name: "Vehicles",
    image_uri: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=400&fit=crop",
  },
  {
    id: 7,
    name: "Appliances",
    image_uri: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop",
  },
  {
    id: 8,
    name: "Electronics",
    image_uri: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=400&fit=crop",
  },
  {
    id: 9,
    name: "Sports",
    image_uri: "https://images.unsplash.com/photo-1461896836934-bd45ba8e6e61?w=400&h=400&fit=crop",
  },
  {
    id: 10,
    name: "Food",
    image_uri: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=400&fit=crop",
  },
  {
    id: 11,
    name: "Books",
    image_uri: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=400&fit=crop",
  },
  {
    id: 12,
    name: "Kids Toys",
    image_uri: "https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400&h=400&fit=crop",
  },
];

const productData = [
  // ── Fashion (8 products) ──────────────────────────────────────
  {
    name: "Slim Fit Jeans",
    price: 1999,
    description: "Stylish slim fit jeans with a comfortable stretch for everyday wear. Made from premium denim with just the right amount of flex.",
    image_uri: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "WAIST_INCH",
    color: "Blue",
    brand: "Killer",
  },
  {
    name: "Men's Casual Shirt",
    price: 1499,
    description: "A lightweight casual shirt for men, perfect for both work and play. Breathable cotton blend fabric.",
    image_uri: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "GENERIC",
    color: "White",
    brand: "Deneeja",
  },
  {
    name: "Women's High Heel Shoes",
    price: 2999,
    description: "Elegant high heel shoes for women, ideal for evening events and parties. Premium faux leather with cushioned insole.",
    image_uri: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "SHOES_UK_WOMEN",
    color: "Black",
    brand: "Gardin",
  },
  {
    name: "Men's Winter Coat",
    price: 4999,
    description: "A warm and stylish winter coat designed to keep you comfortable and fashionable during cold weather.",
    image_uri: "https://images.unsplash.com/photo-1544923246-77307dd270b3?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "GENERIC",
    color: "Black",
    brand: "CHKOKKO",
  },
  {
    name: "Women's Leather Handbag",
    price: 3499,
    description: "A sleek genuine leather handbag for women, perfect for any occasion. Multiple compartments for easy organization.",
    image_uri: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "NONE",
    color: "Brown",
    brand: "Classy Leather",
  },
  {
    name: "Men's Jogger Pants",
    price: 1299,
    description: "Comfortable and sporty jogger pants, perfect for workouts or casual outings. Soft cotton terry fabric.",
    image_uri: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "GENERIC",
    color: "Grey",
    brand: "NOBERO",
  },
  {
    name: "Men's Denim Jacket",
    price: 2499,
    description: "A classic denim jacket that pairs well with almost any outfit. Rugged, durable, and endlessly stylish.",
    image_uri: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "GENERIC",
    color: "Blue",
    brand: "Kotty",
  },
  {
    name: "Women's Floral Dress",
    price: 1899,
    description: "A beautiful floral dress ideal for spring and summer, featuring a flattering A-line silhouette.",
    image_uri: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Fashion",
    sizeType: "GENERIC",
    color: "Green",
    brand: "Drape & Dazzle",
  },

  // ── Electronics (5 products) ──────────────────────────────────
  {
    name: "Wireless Bluetooth Headphones",
    price: 2499,
    description: "Premium over-ear wireless headphones with active noise cancellation, 30-hour battery life, and deep bass.",
    image_uri: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Electronics",
    sizeType: "NONE",
    color: "Black",
    brand: "boAt",
  },
  {
    name: "Smart Watch Pro",
    price: 4999,
    description: "Feature-packed smartwatch with heart rate monitor, SpO2, GPS tracking, and 7-day battery life. Water resistant to 50m.",
    image_uri: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Electronics",
    sizeType: "NONE",
    color: "Black",
    brand: "Noise",
  },
  {
    name: "Portable Bluetooth Speaker",
    price: 1999,
    description: "Compact waterproof Bluetooth speaker with 360° surround sound, 12-hour playtime, and built-in microphone.",
    image_uri: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Electronics",
    sizeType: "NONE",
    color: "Blue",
    brand: "JBL",
  },
  {
    name: "USB-C Fast Charger 65W",
    price: 1299,
    description: "Ultra-fast 65W GaN charger with USB-C and USB-A ports. Compatible with laptops, phones, and tablets.",
    image_uri: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Electronics",
    sizeType: "NONE",
    color: "White",
    brand: "Ambrane",
  },
  {
    name: "Mechanical Gaming Keyboard",
    price: 3499,
    description: "RGB mechanical keyboard with hot-swappable switches, N-key rollover, and aircraft-grade aluminium frame.",
    image_uri: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Electronics",
    sizeType: "NONE",
    color: "Black",
    brand: "Cosmic Byte",
  },

  // ── Mobiles (4 products) ──────────────────────────────────────
  {
    name: "Galaxy S24 Ultra",
    price: 129999,
    description: "Flagship smartphone with 200MP camera, S Pen, Snapdragon 8 Gen 3, 6.8\" Dynamic AMOLED display, and 5000mAh battery.",
    image_uri: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Mobiles",
    sizeType: "NONE",
    color: "Titanium Gray",
    brand: "Samsung",
  },
  {
    name: "iPhone 15 Pro Max",
    price: 159900,
    description: "Apple's most advanced iPhone with A17 Pro chip, titanium design, 48MP camera system, and USB-C with USB 3 speeds.",
    image_uri: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Mobiles",
    sizeType: "NONE",
    color: "Natural Titanium",
    brand: "Apple",
  },
  {
    name: "OnePlus 12",
    price: 64999,
    description: "Performance beast with Snapdragon 8 Gen 3, 100W SUPERVOOC charging, Hasselblad camera, and 2K 120Hz ProXDR display.",
    image_uri: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Mobiles",
    sizeType: "NONE",
    color: "Silky Black",
    brand: "OnePlus",
  },
  {
    name: "Redmi Note 13 Pro+",
    price: 29999,
    description: "Mid-range powerhouse with 200MP camera, 120W HyperCharge, 120Hz curved AMOLED display, and IP68 rating.",
    image_uri: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Mobiles",
    sizeType: "NONE",
    color: "Midnight Black",
    brand: "Xiaomi",
  },

  // ── Home (4 products) ─────────────────────────────────────────
  {
    name: "Cotton Bedsheet Set (King)",
    price: 1299,
    description: "Luxurious 300 thread count cotton bedsheet set with 2 pillow covers. Soft, breathable, and wrinkle-resistant.",
    image_uri: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Home",
    sizeType: "NONE",
    color: "White",
    brand: "Bombay Dyeing",
  },
  {
    name: "Scented Candle Gift Set",
    price: 799,
    description: "Set of 4 premium soy wax scented candles in lavender, vanilla, jasmine, and sandalwood. 30-hour burn time each.",
    image_uri: "https://images.unsplash.com/photo-1602028915047-37269d1a73f7?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Home",
    sizeType: "NONE",
    color: "Multi",
    brand: "Ekam",
  },
  {
    name: "Wall Mounted Shelf Set",
    price: 1499,
    description: "Set of 3 floating wooden wall shelves in a modern minimalist design. Easy to install, holds up to 5 kg each.",
    image_uri: "https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Home",
    sizeType: "NONE",
    color: "Walnut",
    brand: "Decorasia",
  },
  {
    name: "Indoor Plant Pot (Ceramic)",
    price: 599,
    description: "Handcrafted ceramic plant pot with drainage hole and saucer. Perfect for small to medium indoor plants.",
    image_uri: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Home",
    sizeType: "NONE",
    color: "White",
    brand: "Kraft Seeds",
  },

  // ── Gadgets (4 products) ──────────────────────────────────────
  {
    name: "Wireless Earbuds Pro",
    price: 1799,
    description: "True wireless earbuds with active noise cancellation, 28-hour total battery, and IPX5 water resistance.",
    image_uri: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Gadgets",
    sizeType: "NONE",
    color: "White",
    brand: "boAt",
  },
  {
    name: "Power Bank 20000mAh",
    price: 1499,
    description: "Slim 20000mAh power bank with 22.5W fast charging, dual USB output, and LED display for battery percentage.",
    image_uri: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Gadgets",
    sizeType: "NONE",
    color: "Black",
    brand: "Mi",
  },
  {
    name: "Smart LED Bulb (WiFi)",
    price: 699,
    description: "16 million color WiFi smart bulb compatible with Alexa and Google Home. Dimmable, schedule, and voice control.",
    image_uri: "https://images.unsplash.com/photo-1550985616-10810253b84d?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Gadgets",
    sizeType: "NONE",
    color: "White",
    brand: "Wipro",
  },
  {
    name: "Fitness Tracker Band",
    price: 999,
    description: "Sleek fitness band with heart rate, sleep tracking, 14 sport modes, and 10-day battery. Water resistant IP68.",
    image_uri: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Gadgets",
    sizeType: "NONE",
    color: "Black",
    brand: "Realme",
  },

  // ── Beauty (5 products) ───────────────────────────────────────
  {
    name: "Vitamin C Face Serum",
    price: 499,
    description: "Brightening face serum with 15% Vitamin C, hyaluronic acid, and niacinamide. Reduces dark spots and evens skin tone.",
    image_uri: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Beauty",
    sizeType: "VOLUME_ML",
    color: null,
    brand: "Plum",
  },
  {
    name: "Matte Liquid Lipstick Set",
    price: 799,
    description: "Set of 4 long-lasting matte liquid lipsticks in versatile shades. Transfer-proof, lightweight formula.",
    image_uri: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Beauty",
    sizeType: "NONE",
    color: "Multi",
    brand: "SUGAR",
  },
  {
    name: "Sunscreen SPF 50+ PA+++",
    price: 399,
    description: "Lightweight, non-greasy sunscreen with broad spectrum UVA/UVB protection. Suitable for all skin types.",
    image_uri: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Beauty",
    sizeType: "VOLUME_ML",
    color: null,
    brand: "Minimalist",
  },
  {
    name: "Hair Dryer 2200W",
    price: 1599,
    description: "Professional ionic hair dryer with 3 heat settings, cool shot button, and concentrator nozzle. Reduces frizz.",
    image_uri: "https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Beauty",
    sizeType: "NONE",
    color: "Pink",
    brand: "Philips",
  },
  {
    name: "Charcoal Face Wash",
    price: 299,
    description: "Deep cleansing charcoal face wash that removes dirt, oil, and impurities. Enriched with tea tree and salicylic acid.",
    image_uri: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Beauty",
    sizeType: "VOLUME_ML",
    color: null,
    brand: "mCaffeine",
  },

  // ── Sports (4 products) ───────────────────────────────────────
  {
    name: "Men's Running Shoes",
    price: 2999,
    description: "Lightweight running shoes with responsive cushioning, breathable mesh upper, and durable rubber outsole.",
    image_uri: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Sports",
    sizeType: "SHOES_UK_MEN",
    color: "Black",
    brand: "Nike",
  },
  {
    name: "Yoga Mat (6mm Anti-Slip)",
    price: 899,
    description: "Premium 6mm thick TPE yoga mat with anti-slip texture on both sides. Includes carry strap. Eco-friendly material.",
    image_uri: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Sports",
    sizeType: "NONE",
    color: "Purple",
    brand: "Boldfit",
  },
  {
    name: "Adjustable Dumbbell Set (20kg)",
    price: 3999,
    description: "Pair of adjustable dumbbells with vinyl-coated weight plates. Total 20 kg. Perfect for home workouts.",
    image_uri: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Sports",
    sizeType: "WEIGHT_G",
    color: "Black",
    brand: "Kore",
  },
  {
    name: "Cricket Bat (English Willow)",
    price: 5999,
    description: "Grade A English willow cricket bat with thick edges and sweet spot. Ideal for leather ball cricket.",
    image_uri: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Sports",
    sizeType: "NONE",
    color: "Natural",
    brand: "SG",
  },

  // ── Appliances (4 products) ───────────────────────────────────
  {
    name: "Mixer Grinder 750W",
    price: 3499,
    description: "Powerful 750W mixer grinder with 3 stainless steel jars, 3-speed control, and overload protection.",
    image_uri: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Appliances",
    sizeType: "NONE",
    color: "Red",
    brand: "Bajaj",
  },
  {
    name: "Air Purifier (HEPA Filter)",
    price: 7999,
    description: "Room air purifier with true HEPA H13 filter, activated carbon layer, and real-time AQI display. Covers 400 sq ft.",
    image_uri: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Appliances",
    sizeType: "NONE",
    color: "White",
    brand: "Mi",
  },
  {
    name: "Electric Kettle 1.5L",
    price: 899,
    description: "Stainless steel electric kettle with auto shut-off, boil-dry protection, and 360° swivel base.",
    image_uri: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Appliances",
    sizeType: "NONE",
    color: "Silver",
    brand: "Prestige",
  },
  {
    name: "Robot Vacuum Cleaner",
    price: 12999,
    description: "Smart robot vacuum with LiDAR navigation, 2700Pa suction, mopping function, and app control. 150-minute runtime.",
    image_uri: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Appliances",
    sizeType: "NONE",
    color: "White",
    brand: "ECOVACS",
  },

  // ── Books (4 products) ────────────────────────────────────────
  {
    name: "Atomic Habits - James Clear",
    price: 399,
    description: "The #1 bestseller on building good habits and breaking bad ones. Practical strategies backed by science.",
    image_uri: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Books",
    sizeType: "NONE",
    color: null,
    brand: "Penguin",
  },
  {
    name: "The Psychology of Money",
    price: 349,
    description: "Morgan Housel's timeless lessons on wealth, greed, and happiness. A must-read for anyone interested in finance.",
    image_uri: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Books",
    sizeType: "NONE",
    color: null,
    brand: "Jaico",
  },
  {
    name: "Head First JavaScript Programming",
    price: 899,
    description: "An in-depth guide to JavaScript programming using a visually rich format. Covers ES6+, DOM, events, and more.",
    image_uri: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Books",
    sizeType: "NONE",
    color: null,
    brand: "O'Reilly",
  },
  {
    name: "Rich Dad Poor Dad",
    price: 299,
    description: "Robert Kiyosaki's classic on personal finance and the mindset shift needed to build wealth. Over 32 million copies sold.",
    image_uri: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=500&h=600&fit=crop",
    ar_uri: null,
    category: "Books",
    sizeType: "NONE",
    color: null,
    brand: "Plata Publishing",
  },

  // ── Food (4 products) ─────────────────────────────────────────
  {
    name: "Premium Dry Fruits Gift Box",
    price: 1299,
    description: "Assorted premium dry fruits including almonds, cashews, pistachios, and walnuts in a luxurious gift box (500g).",
    image_uri: "https://images.unsplash.com/photo-1604085572504-a392541f0b40?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Food",
    sizeType: "WEIGHT_G",
    color: null,
    brand: "Happilo",
  },
  {
    name: "Organic Green Tea (100 bags)",
    price: 449,
    description: "100% certified organic green tea bags. Rich in antioxidants with a smooth, refreshing taste. No artificial flavors.",
    image_uri: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Food",
    sizeType: "NONE",
    color: null,
    brand: "Organic India",
  },
  {
    name: "Dark Chocolate Bar (72% Cocoa)",
    price: 199,
    description: "Single-origin dark chocolate with 72% cocoa. Rich, smooth, and ethically sourced. 80g bar.",
    image_uri: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Food",
    sizeType: "NONE",
    color: null,
    brand: "Amul",
  },
  {
    name: "Protein Peanut Butter (1kg)",
    price: 599,
    description: "High-protein crunchy peanut butter with no added sugar. 30g protein per 100g. Gluten-free and vegan.",
    image_uri: "https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Food",
    sizeType: "WEIGHT_G",
    color: null,
    brand: "MyFitness",
  },

  // ── Kids Toys (4 products) ────────────────────────────────────
  {
    name: "Building Blocks Set (200 pcs)",
    price: 999,
    description: "Colorful interlocking building blocks compatible with major brands. 200 pieces in a storage bucket. Ages 3+.",
    image_uri: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Kids Toys",
    sizeType: "NONE",
    color: "Multi",
    brand: "LEGO",
  },
  {
    name: "Remote Control Car (RC Racing)",
    price: 1499,
    description: "High-speed RC racing car with 2.4GHz remote, rechargeable battery, and working LED headlights. Top speed 25 km/h.",
    image_uri: "https://images.unsplash.com/photo-1581235707960-35f13e445e72?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Kids Toys",
    sizeType: "NONE",
    color: "Red",
    brand: "Hot Wheels",
  },
  {
    name: "Educational Puzzle Board",
    price: 499,
    description: "Wooden alphabet and number puzzle board for toddlers. Develops motor skills and letter recognition. Ages 2–5.",
    image_uri: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Kids Toys",
    sizeType: "NONE",
    color: "Multi",
    brand: "FunBlast",
  },
  {
    name: "Soft Toy Teddy Bear (2ft)",
    price: 699,
    description: "Super soft plush teddy bear, 2 feet tall. Made with hypoallergenic filling. Perfect birthday gift for kids.",
    image_uri: "https://images.unsplash.com/photo-1559715541-5daf8a0296d0?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Kids Toys",
    sizeType: "NONE",
    color: "Brown",
    brand: "Dimpy Stuff",
  },

  // ── Vehicles (4 products) ─────────────────────────────────────
  {
    name: "Car Phone Mount (Magnetic)",
    price: 599,
    description: "Strong magnetic car phone holder with 360° rotation. Air vent mount, compatible with all smartphones.",
    image_uri: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Vehicles",
    sizeType: "NONE",
    color: "Black",
    brand: "ZAAP",
  },
  {
    name: "Dash Cam 1080p",
    price: 2999,
    description: "Full HD 1080p dash camera with night vision, 170° wide angle, loop recording, and G-sensor for parking mode.",
    image_uri: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Vehicles",
    sizeType: "NONE",
    color: "Black",
    brand: "70mai",
  },
  {
    name: "Car Seat Cover Set",
    price: 1999,
    description: "Premium faux leather car seat cover set for 5-seater vehicles. Universal fit, waterproof, and easy to install.",
    image_uri: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Vehicles",
    sizeType: "NONE",
    color: "Black",
    brand: "AutoFurnish",
  },
  {
    name: "Tyre Inflator (Digital)",
    price: 1499,
    description: "Portable digital tyre inflator with auto shut-off, LED display, and preset pressure. Works on 12V car socket.",
    image_uri: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=500&h=500&fit=crop",
    ar_uri: null,
    category: "Vehicles",
    sizeType: "NONE",
    color: "Yellow",
    brand: "ResQTech",
  },
];

module.exports = { categoriesData, productData };
